replicaCount: 1
image:
  repository: peteindockerhub/hello-rancher
  pullPolicy: Always
  tag: "1.0.0"

ports:
    containerPort: 8080
    protocol: TCP

service:
  type: ClusterIP
  port: 80
  targetPort: 8080
  protocol: TCP

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: hello-matheus.aula.jac.bsb.br
      paths:
        - path: /
          pathType: ImplementationSpecific

resources:
limits:
  cpu: 100m
  memory: 128Mi
requests:
  cpu: 100m
  memory: 128Mi
